# Generated by Django 3.2.7 on 2021-09-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('category', models.IntegerField(choices=[(1, 'Technology'), (2, 'Travel'), (3, 'Music'), (4, 'Lifestyle'), (5, 'Sports'), (6, 'Finance'), (7, 'Political'), (8, 'Business'), (9, 'Personal'), (10, 'Movie'), (11, 'Car'), (12, 'Gaming')])),
                ('text', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
